platform :ios, '10.0'

use_frameworks!

target 'ExampleConference' do
  pod 'AuviousSDK', :path => '../'
  pod 'SVProgressHUD', :git => 'https://github.com/mmdock/SVProgressHUD.git', :branch => 'patch-1'
  pod 'SPPermissions/Camera', '~> 4.1'
  pod 'SPPermissions/Microphone', '~> 4.1'
  pod 'BEMCheckBox', '~> 1.4'
  pod 'Sentry', '~> 4.4'
end

target 'ExampleCall' do
  pod 'AuviousSDK', :path => '../'
  pod 'SVProgressHUD', :git => 'https://github.com/mmdock/SVProgressHUD.git', :branch => 'patch-1'
  pod 'SPPermissions/Camera', '~> 4.1'
  pod 'SPPermissions/Microphone', '~> 4.1'
  pod 'BEMCheckBox', '~> 1.4'
  pod 'Sentry', '~> 4.4'
end

target 'ExampleSimpleCall' do
  pod 'AuviousSDK', :path => '../'
  pod 'Sentry', '~> 4.4'
end

target 'ExampleSimpleConference' do
  pod 'AuviousSDK', :path => '../'
  pod 'Sentry', '~> 4.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Alamofire', 'SwiftyJSON'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end

