platform :ios, '13.0'

#source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/auvious/CocoaPodSpecs.git'

use_frameworks!

target 'ExampleConference' do
  pod 'AuviousSDK', :path => '../'
  pod 'SVProgressHUD', :git => 'https://github.com/mmdock/SVProgressHUD.git', :branch => 'patch-1'
  pod 'SPPermissions/Camera', '~> 4.1'
  pod 'SPPermissions/Microphone', '~> 4.1'
  pod 'BEMCheckBox', '~> 1.4'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.46.0'
end

target 'ExampleCall' do
  pod 'AuviousSDK', :path => '../'
  pod 'SVProgressHUD', :git => 'https://github.com/mmdock/SVProgressHUD.git', :branch => 'patch-1'
  pod 'SPPermissions/Camera', '~> 4.1'
  pod 'SPPermissions/Microphone', '~> 4.1'
  pod 'BEMCheckBox', '~> 1.4'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.46.0'
end

target 'ExampleSimpleCall' do
  pod 'AuviousSDK', :path => '../'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.46.0'
end

target 'ExampleSimpleConference' do
  pod 'AuviousSDK', :path => '../'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.46.0'
end

post_install do |installer|
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
      end
  end
  
  installer.pods_project.targets.each do |target|
    if ['Alamofire', 'SwiftyJSON'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
